# Generated by Django 5.1.4 on 2024-12-28 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exam_teacher_alter_exam_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
