# Generated by Django 5.1.4 on 2024-12-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_exam_teacher_alter_exam_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
