# Generated by Django 5.1.4 on 2025-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_allow_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('rattrapage', 'Rattrapage')], default='normal', max_length=15),
        ),
    ]
