# Generated by Django 5.1.4 on 2025-01-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_examattempt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
