# Generated by Django 5.1.4 on 2025-01-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_examattempt_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('page_load', 'Page Loaded'), ('page_unload', 'Page Unloaded'), ('tab_switch', 'Tab Switched'), ('navigation_attempt', 'Navigation Attempt'), ('question_answered', 'Question Answered'), ('inactivity_detected', 'Inactivity Detected'), ('copy_attempt', 'Copy Attempt'), ('screen_resize', 'Screen Resized'), ('suspicious_shortcut', 'Suspicious Shortcut Used')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examattempt')),
            ],
        ),
    ]
