# Generated by Django 5.1.4 on 2025-01-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quiz_quizattempt_quizquestion_quizchoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizchoice',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Allow students to review their answers after submission'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each attempt'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_score_immediately',
            field=models.BooleanField(default=True, help_text='Show score immediately after submission'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent',
            field=models.DurationField(blank=True, help_text='Total time spent on the quiz', null=True),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the choice in the question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False, help_text='Allow selecting multiple choices'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Question must be answered'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='response_time',
            field=models.DurationField(blank=True, help_text='Time taken to answer this question', null=True),
        ),
    ]
