# Generated by Django 5.1.4 on 2025-01-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_quizchoice_options_quiz_allow_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-start_time'], 'verbose_name': 'Tentative', 'verbose_name_plural': 'Tentatives'},
        ),
        migrations.AlterModelOptions(
            name='quizchoice',
            options={'ordering': ['order'], 'verbose_name': 'Choix', 'verbose_name_plural': 'Choix'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizresponse',
            options={'verbose_name': 'Réponse', 'verbose_name_plural': 'Réponses'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='allow_review',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_score_immediately',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Montrer les réponses correctes après la soumission'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.FloatField(default=50.0, help_text='Score minimum requis en pourcentage'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text="Mélanger l'ordre des questions pour chaque tentative"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Durée en minutes', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('timed_out', 'Temps écoulé')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explication pour cette réponse', null=True),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False, help_text='Permettre la sélection de plusieurs réponses'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explication affichée après la réponse', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='La question doit être répondue'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
