# Generated by Django 5.1.5 on 2025-01-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_questionbank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Question_Quiz', 'verbose_name_plural': 'Questions Quiz'},
        ),
    ]
