# Generated by Django 5.1.5 on 2025-01-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_quizquestion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='year',
        ),
    ]
