# Generated by Django 5.1.5 on 2025-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_group_end_year_group_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='in_progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='studentactionlog',
            name='action',
            field=models.CharField(choices=[('Suspicious shortcut', 'Suspicious Shortcut Used'), ('Copy attempt', 'Copy Attempt'), ('Network disconnect', 'Network Disconnected'), ('Screen resize', 'Screen Resized'), ('Context menu', 'Context Menu Opened'), ('Dev tools', 'Developer Tools Opened'), ('Extended disconnect', 'Extended Network Disconnect'), ('Mouse leave', 'Mouse Left Window'), ('Focus lost', 'Window Focus Lost'), ('Text selection', 'Text Selection Attempted'), ('Network reconnect', 'Network Reconnected'), ('question_answered', 'Question Answered'), ('inactivity_detected', 'Inactivity Detected')], max_length=50),
        ),
    ]
