# Generated by Django 5.1.5 on 2025-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_examattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_taking_exam',
            field=models.BooleanField(default=False),
        ),
    ]
