# Generated by Django 5.1.5 on 2025-02-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_exam_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
