# Generated by Django 5.1.5 on 2025-02-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_exam_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='max_attempts',
        ),
    ]
