# Generated by Django 5.1.5 on 2025-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_exam_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='quizchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='selected_choices',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizChoice',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
